name: party_planner
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  onboarding: ^4.0.2
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  flutter_email_sender: ^6.0.3
  pull_down_button: ^0.10.2
  calendar_date_picker2: ^1.1.7
  flutter_svg: ^2.0.14
  easy_date_timeline: ^1.1.3
  sqflite: ^2.3.3
  custom_progressbar: ^0.0.2
  is_first_run: ^1.0.0
  shared_preferences: ^2.0.6
  custom_sliding_segmented_control: ^1.8.4
  flutter_slidable: ^3.1.1
  flutter_markdown: ^0.7.4+1
  equatable: ^2.0.5
  webview_flutter: ^4.10.0
  cupertino_icons: ^1.0.6
  flagsmith: ^6.0.0
  url_launcher: ^6.3.1
  get_ip_address: ^0.0.7
  in_app_review: ^2.0.10
  flutter_native_splash: ^2.4.3
  webview_flutter_wkwebview: ^3.16.3

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#FFFFFF" 
  image: Assets/Icons/icon.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: Assets/Icons/icon.png



  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  assets:
    - Assets/
    - Assets/Icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: Assets/Fonts/Poppins-Regular.ttf
        - asset: Assets/Fonts/Poppins-Bold.ttf
          weight: 700

